[package]
name = "earwax"
version = "0.1.7"
authors = ["Daniel Rivas <ers.daniel+dev@gmail.com>"]
build = "build.rs"

description = "Audio decoding library for Rust based on ffmpeg"

homepage = "https://github.com/danielrs/earwax"
documentation = "https://docs.rs/earwax"
repository = "https://github.com/danielrs/earwax"

license-file = "./LICENSE"
<<<<<<< HEAD
edition = "2018"

[dependencies]
libc = "0.2"
num = "0.2"

[dev-dependencies]
ao_rs = "0.1"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = true
codegen-units = 1
=======

[dependencies]
libc = "0.2"
num = "0.1"

[dev-dependencies]
ao_rs = "0.1.0"

[build-dependencies]
gcc = "0.3"
>>>>>>> parent of 5d79726... Update dependencies, fix deprecation warnings
